-- =====================================================
-- COOPERATIVA BEB - DDL Tablas principales
-- Oracle 11g XE
-- =====================================================

-- Limpiar tablas si existen (orden inverso por FK)
DROP TABLE TRANSACCION CASCADE CONSTRAINTS PURGE;
DROP TABLE PLAN_INVERSION CASCADE CONSTRAINTS PURGE;
DROP TABLE CUENTA_AHORRO CASCADE CONSTRAINTS PURGE;
DROP TABLE PRODUCTO_FINANCIERO CASCADE CONSTRAINTS PURGE;
DROP TABLE ASESOR_FINANCIERO CASCADE CONSTRAINTS PURGE;
DROP TABLE CLIENTE CASCADE CONSTRAINTS PURGE;

-- =====================================================
-- TABLA: CLIENTE
-- =====================================================
CREATE TABLE CLIENTE (
    id_cliente      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dni             VARCHAR2(8)    NOT NULL UNIQUE,
    nombres         VARCHAR2(100)  NOT NULL,
    apellidos       VARCHAR2(100)  NOT NULL,
    telefono        VARCHAR2(15),
    email           VARCHAR2(100)  UNIQUE,
    fecha_nacimiento DATE,
    direccion       VARCHAR2(200),
    estado          VARCHAR2(10)   DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO','INACTIVO')),
    fecha_registro  DATE           DEFAULT SYSDATE NOT NULL
);

-- =====================================================
-- TABLA: ASESOR_FINANCIERO
-- =====================================================
CREATE TABLE ASESOR_FINANCIERO (
    id_asesor       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dni             VARCHAR2(8)    NOT NULL UNIQUE,
    nombres         VARCHAR2(100)  NOT NULL,
    apellidos       VARCHAR2(100)  NOT NULL,
    especialidad    VARCHAR2(100),
    telefono        VARCHAR2(15),
    email           VARCHAR2(100)  UNIQUE,
    estado          VARCHAR2(10)   DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO','INACTIVO'))
);

-- =====================================================
-- TABLA: PRODUCTO_FINANCIERO
-- =====================================================
CREATE TABLE PRODUCTO_FINANCIERO (
    id_producto     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR2(100)  NOT NULL,
    tipo            VARCHAR2(20)   NOT NULL CHECK (tipo IN ('AHORRO','CREDITO','INVERSION')),
    descripcion     VARCHAR2(300),
    tasa_base       NUMBER(5,2)    NOT NULL,
    monto_minimo    NUMBER(12,2)   DEFAULT 0,
    monto_maximo    NUMBER(12,2),
    plazo_meses     NUMBER(3),
    estado          VARCHAR2(10)   DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO','INACTIVO'))
);

-- =====================================================
-- TABLA: CUENTA_AHORRO
-- =====================================================
CREATE TABLE CUENTA_AHORRO (
    id_cuenta       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nro_cuenta      VARCHAR2(20)   NOT NULL UNIQUE,
    id_cliente      NUMBER         NOT NULL,
    id_asesor       NUMBER,
    saldo           NUMBER(12,2)   DEFAULT 0 NOT NULL,
    tasa_interes    NUMBER(5,2)    DEFAULT 0.5,
    tipo_cuenta     VARCHAR2(20)   DEFAULT 'BASICA' CHECK (tipo_cuenta IN ('BASICA','PREMIUM','INFANTIL')),
    estado          VARCHAR2(10)   DEFAULT 'ACTIVA' CHECK (estado IN ('ACTIVA','CERRADA','BLOQUEADA')),
    fecha_apertura  DATE           DEFAULT SYSDATE NOT NULL,
    fecha_cierre    DATE,
    CONSTRAINT fk_cuenta_cliente FOREIGN KEY (id_cliente) REFERENCES CLIENTE(id_cliente),
    CONSTRAINT fk_cuenta_asesor  FOREIGN KEY (id_asesor)  REFERENCES ASESOR_FINANCIERO(id_asesor)
);

-- =====================================================
-- TABLA: PLAN_INVERSION
-- =====================================================
CREATE TABLE PLAN_INVERSION (
    id_plan         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente      NUMBER         NOT NULL,
    id_producto     NUMBER         NOT NULL,
    id_asesor       NUMBER,
    monto_invertido NUMBER(12,2)   NOT NULL,
    tasa_pactada    NUMBER(5,2)    NOT NULL,
    plazo_meses     NUMBER(3)      NOT NULL,
    fecha_inicio    DATE           DEFAULT SYSDATE NOT NULL,
    fecha_vencimiento DATE         NOT NULL,
    estado          VARCHAR2(10)   DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO','VENCIDO','CANCELADO')),
    CONSTRAINT fk_plan_cliente   FOREIGN KEY (id_cliente)  REFERENCES CLIENTE(id_cliente),
    CONSTRAINT fk_plan_producto  FOREIGN KEY (id_producto) REFERENCES PRODUCTO_FINANCIERO(id_producto),
    CONSTRAINT fk_plan_asesor    FOREIGN KEY (id_asesor)   REFERENCES ASESOR_FINANCIERO(id_asesor)
);

-- =====================================================
-- TABLA: TRANSACCION
-- =====================================================
CREATE TABLE TRANSACCION (
    id_transaccion  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cuenta       NUMBER,
    id_plan         NUMBER,
    tipo            VARCHAR2(20)   NOT NULL CHECK (tipo IN ('DEPOSITO','RETIRO','TRANSFERENCIA','INTERES','APERTURA','CIERRE')),
    monto           NUMBER(12,2)   NOT NULL,
    saldo_anterior  NUMBER(12,2)   NOT NULL,
    saldo_posterior NUMBER(12,2)   NOT NULL,
    fecha_transaccion DATE         DEFAULT SYSDATE NOT NULL,
    descripcion     VARCHAR2(300),
    estado          VARCHAR2(10)   DEFAULT 'EXITOSA' CHECK (estado IN ('EXITOSA','FALLIDA','PENDIENTE')),
    CONSTRAINT fk_trans_cuenta FOREIGN KEY (id_cuenta) REFERENCES CUENTA_AHORRO(id_cuenta),
    CONSTRAINT fk_trans_plan   FOREIGN KEY (id_plan)   REFERENCES PLAN_INVERSION(id_plan),
    CONSTRAINT chk_trans_origen CHECK (id_cuenta IS NOT NULL OR id_plan IS NOT NULL)
);

-- =====================================================
-- INDICES para optimizar consultas
-- =====================================================
CREATE INDEX idx_cuenta_cliente   ON CUENTA_AHORRO(id_cliente);
CREATE INDEX idx_plan_cliente     ON PLAN_INVERSION(id_cliente);
CREATE INDEX idx_trans_cuenta     ON TRANSACCION(id_cuenta);
CREATE INDEX idx_trans_fecha      ON TRANSACCION(fecha_transaccion);
CREATE INDEX idx_cliente_dni      ON CLIENTE(dni);

COMMIT;

-- Verificar tablas creadas
SELECT table_name FROM user_tables ORDER BY table_name;
